### ISSUE TITLE
Using RestApi based on --verbose parameters - How to?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [hyperonecom/h1-cli#225]
I've been playing a bit with CLI in powershell. 

```
Start-Process -Wait -NoNewWindow $Binary -ArgumentList 'project', 'list', '-o', 'json', '--verbose'
```

This gives me:

```
verbose: GET https://api.hyperone.com/v1/project
verbose: query {"active":true}
verbose: 200 OK
<json output>
```

Now if I would want to use that to invoke rest directly:

```
Invoke-RestMethod -Uri 'https://api.hyperone.com/v1/project'
```

I need to give it additional parameters. For that I need a how-to. Otherwise I get an error:

![image](https://user-images.githubusercontent.com/15063294/46158571-6fabd480-c27e-11e8-95b1-e3771a1de6b1.png)

And this becomes more or less a bit problematic to try and use CLI for learning on RestApi purposes.

**Comment by ad-m** [comment]
Thank you for reporting. It pushes us more and more in the API documentation generation process.

I don't have any knowledge regarding to PowerShell, but I hope you able to transpile curl command to appropriate example.

Most API methods require authentication. Authentication is carried out by sending:
- token for user
- token for the service account
Both of them you should send them in header ```x-auth-token```.
Most of operation (when token for user is used only, because service account is project-specific) require providing also project identifier. That values show be passed in header ```x-project```.

At that moment (until we finish of process of documentation of API generation, which exists on our road map) to discovery our API you can use CLI in ``--verbose``` mode.  For example using CLI you can get following result:
```
$ h1 vm list -v
verbose: GET https://api.hyperone.com/v1/vm
verbose: headers
{
  "x-auth-token": "253bcac7dd806bb7cf57dc19f71f2fa0",
  "x-project": "30cf3d7d133b08543cb6c8933c29dfd7"
}
verbose: query {}
verbose: 200 OK
ID                        NAME        FLAVOUR    STATE  TAGS
5b698289d242500e34ae43b6  vm-windows  m2.medium  Off    
```
That request using only curl can be done in that way:
```bash
curl -X GET -H 'x-auth-token: 253bcac7dd806bb7cf57dc19f71f2fa0' -H 'x-project: 30cf3d7d133b08543cb6c8933c29dfd7' 'https://api.hyperone.com/v1/vm'
```

**Comment by PrzemyslawKlys** [comment]
How do I get token for user, token for service account and x-project value? CURL method is fine. I just need to know where to get those values to use with curl.

**Comment by ad-m** [comment]
@PrzemyslawKlys , obtaining a user's token key for user require full authentication of user. There is different way to authenticate user for different purposes.

# SSH authentication

Uses private key from local ssh-agent and match to user public key uploaded. 

How to add ssh key, see ```h1 user credentials add --help``` . 

To obtain token you need connect to our auth server using key uploaded to our platform. For that on Linux you can use following command:
```
ssh -o "User=user@email.com" api.hyperone.com -s rbx-auth
``` 
ECDSA key fingerprint of auth server is ```SHA256:5NMT5Ii36+8F+Go/2Kr4Ouce22kT+8iiNLp4f+2/nhQ```.

# login & password 

## without 2-factor authentication

```
curl -X POST https://api.hyperone.com/v1/user/user@example.com/session -H 'Content-Type: application/json' -d '{"password": "STRON_SECRET"}' -v
```

Status codes:

- 200 - authorized, response contains apiKey,
- 403 and request contains "CHALLENGE_REQUEST" - partially authorized, 2-factor authentication required to obtain user token

## with 2-factor authentication using TOTP

```
 curl -X POST https://api.hyperone.com/v1/user/user@password.com/session -H 'Content-Type: application/json' -d '{"password": "STRONG_SECRET", "challenge": {"totp":774144}}' -v
```

## with 2-factor authentication using backup codes

```
 curl -X POST https://api.hyperone.com/v1/user/user@password.com/session -H 'Content-Type: application/json' -d '{"password": "STRONG_SECRET", "challenge": {"otac":"xxxxxx"}}' -v
```

# Service account

I think it is the simplest way in this case. This is the recommended way to access the platform for scripts and other automated tools.

Using CLI execute following command:
```bash
$ h1 project token add --name my-cool-project -o yaml
```
It provides following result:
```yaml
_id: 253bcac7dd806bb7cf57dc19f71f2fa0
createdBy: user@example.com
createdOn: '2018-09-27T17:26:30.175Z'
access:
  - _id: 3283f1916b2bf8347a4304521e5d7f18
    path: /
    method: ALL
    id: 3283f1916b2bf8347a4304521e5d7f18
name: my-cool-project
```
The value of ```_id``` is token of service account.

The token of service account can be used in following way:
```bash
$ curl -X GET -H 'x-auth-token: 253bcac7dd806bb7cf57dc19f71f2fa0' 'https://api.hyperone.com/v1/vm'
```

As said before, there is no need to specify project. Each service account is created in the context of the selected project and that project is used if necessary.

# x-project

To get value of ```x-project``` for request using user token execute command:
```bash
h1 project list
```
Column "id" contains values for ```x-project``` header.

**Comment by PrzemyslawKlys** [comment]
Ok. So we're almost there yet. 

![image](https://user-images.githubusercontent.com/15063294/46170429-1358ad00-c29e-11e8-8563-1358d859be59.png)

This is from this
```
#Start-Process -Wait -NoNewWindow $Binary -ArgumentList 'project', 'list', '-o', 'json', '--verbose'
```
Now if I take

```
curl -X GET -H 'x-auth-token: my token' 'https://api.hyperone.com/v1/project'
```
I get:

```
{"status":403,"message":"project endpoints are disabled"}
```

I surely miss the query part from it:

```
verbose: GET https://api.hyperone.com/v1/project
verbose: query {"active":true}
verbose: 200 OK
```

**Comment by ad-m** [comment]
@PrzemyslawKlys , it looks you attempt to use service accounts to manage projects.. It's not supported. Service Account does not allow to manage projects because:
- each Service Accounts is associated to only one project and there is no way to reach multiple projects using one Service Accounts (isolation by design)
- this is potentially dangerous, because it would allow escalation of permissions, because the "/projects" address contains information about other service account, their tokens and access rights.

We analyze how to extend to provide a read-only of some information about the project, but this should be done carefully, due security risks. This is not the primary goal at this moment.

If you like reach ```/projects``` you need use user token. Here is a condensed example for the Linux platform:
```bash
curl -X GET -H "x-auth-token: $(ssh -o 'User=user@example.com' api.hyperone.com -s rbx-auth | jp -u '_id')" 'https://api.hyperone.com/v1/project'
```

**Comment by ad-m** [comment]
@PrzemyslawKlys , do you need any help? Do you expect any activities from our side apart from completing the documentation of the platform (which goes beyond the CLI itself)? In CLI, the issue seems to be exhausted.
